# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jiaxi He
subtitle: Living and learning in Raleigh
description: Jiaxi He's personal page
author: Jiaxi He
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://henryhoo.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/henryhoo/henryhoo.github.io.git
  branch: [master]
  name: [henryhoo]
  email: [497018787@qq.com]

theme_config:
  baidu_analytics: 5cb1205e2ee7921b3a3636edfe6a588a
  scheme: Pisces
  avatar: /images/avatar.jpg
  sidebar:
    position: left
    display: always
    offset: 12
    b2t: false
    scrollpercent: false
    onmobile: false
  social:
    GitHub: https://github.com/henryhoo || github
    FB Page: https://www.facebook.com/jiaxi.henry.he || facebook
    StackOverflow: https://stackoverflow.com/users/6211857/jiaxi-he || stack-overflow
    Instagram: https://www.instagram.com/jiaxi_h || instagram
    Linkedin: https://www.linkedin.com/in/jiaxih/ || linkedin
  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
  reward_comment: Donate
  wechatpay: /images/wechatpay.jpg
  # other: /images/paypalpay.png
  leancloud_visitors:
    enable: true
    app_id: zRg8LmYzOw19YgrvP6rkepru-gzGzoHsz
    app_key: FsTvxeDNJU2y2eVJMIHoEn1r
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in lc counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set the `security` to `false`.
    security: false
    betterPerformance: false
  gitment:
    enable: true
    mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
    count: true # Show comments count in post meta area
    lazy: false # Comments lazy loading with a button
    cleanly: false # Hide 'Powered by ...' on footer, and more
    language: # Force language, or auto switch by theme
    github_user: henryhoo # MUST HAVE, Your Github ID
    github_repo: gitment-comments # MUST HAVE, The repo you use to store Gitment comments
    client_id: 1bf3b07032854409cd99 # MUST HAVE, Github client id for the Gitment
    client_secret: eefef5b8d79ba2ec15878ee3e547a2271476bf21 # EITHER this or proxy_gateway, Github access secret token for the Gitment
    proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
    redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled
  links_layout: inline
  links:
    Xingyao: http://xingyaohuang.com
    Yiwen: https://yiwencui.wixsite.com/portfolio
  add_this_id: ra-5b1cfece61fa2af8
  local_search:
    enable: true
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # unescape html strings to the readable one
    unescape: true
  footer:
    # Specify the date when the site was setup.
    # If not defined, current year will be used.
    since: 2016
    # Icon between year and copyright info.
    icon:
      # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons
      # `heart` is recommended with animation in red (#ff0000).
      name: user
      # If you want to animate the icon, set it to true.
      animated: false
      # Change the color of icon, using Hex Code.
      color: "#808080"

    # If not defined, will be used `author` from Hexo main config.
    copyright:
    # -------------------------------------------------------------
    powered:
      # Hexo link (Powered by Hexo).
      enable: true
      # Version info of Hexo after Hexo link (vX.X.X).
      version: true

    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: true
      # Version info of NexT after scheme info (vX.X.X).
      version: true
